---
- name: Get node IP from interface
  shell: |
    ip a | grep {{ host_interface }} -A2 | grep 'inet ' | awk '{print $2}' | awk -F/ '{print $1}' | head -1
  register: node_ip

- name: Find kubelet systemd configuration file
  stat:
    path: "{{ item }}"
  register: kubelet_config_files
  loop:
    - /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    - /lib/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: Set kubelet config file path
  set_fact:
    kubelet_systemd_file: "{{ item.item }}"
  when: item.stat.exists
  loop: "{{ kubelet_config_files.results }}"

- name: Fail if kubelet config file not found
  fail:
    msg: "Kubelet systemd config file not found"
  when: kubelet_systemd_file is not defined

- name: Configure kubelet node-ip
  replace:
    path: "{{ kubelet_systemd_file }}"
    regexp: 'Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"'
    replace: 'Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --node-ip={{ node_ip.stdout }}"'
    backup: yes
  notify:
    - reload systemd
    - restart kubelet

- name: Configure file limits
  copy:
    content: '*     -   nofile  165535'
    dest: /etc/security/limits.d/caas.conf

- name: Configure system file limits
  copy:
    content: |
      fs.file-max = 5000000
      fs.inotify.max_user_instances = 256
    dest: /etc/sysctl.d/90-caas-file-limits.conf
  notify: reload sysctl

# Remove master taints if no workers are configured
- name: Check if workers group is empty
  set_fact:
    workers_empty: "{{ groups['workers'] | length == 0 or groups.get('workers', {}).get('hosts', {}) | length == 0 }}"
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Remove control-plane taint when no workers configured
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule- || true
  when: 
    - workers_empty | bool
    - inventory_hostname == groups['masters'][0]  # Only run once from first master with --all
  ignore_errors: true