---
- name: restart chrony
  systemd:
    name: chrony
    state: restarted
    daemon_reload: yes

- name: restart containerd
  systemd:
    name: containerd
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart logrotate
  systemd:
    name: logrotate
    state: restarted