all:
  vars:
    ansible_user: "{{ ansible_ssh_user | default('ubuntu') }}" 
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    masters:
      hosts:   #### The order master1, master2 master3 should be preserved in the array as we area using it to execute master-init and masters join steps
        caas-master-1:
          ansible_host: 10.235.191.40
        caas-master-2:
          ansible_host: 10.235.191.42
        caas-master-3:
          ansible_host: 10.235.191.41
    workers:
      hosts: {} 
    kubernetes:
      children:
        masters: {}
        workers: {}
