all:
  children:
    masters:
      hosts:   #### The order master1, master2 master3 should be preserved in the array as we area using it to execute master-init and masters join steps
        caas-master-1:
          ansible_host: 10.0.1.10
        caas-master-2:
          ansible_host: 10.0.1.11
        caas-master-3:
          ansible_host: 10.0.1.12
    workers:
      hosts:
        caas-worker-1:
          ansible_host: 10.0.1.20
        caas-worker-2:
          ansible_host: 10.0.1.21
    kubernetes:
      children:
        - masters
        - workers

