---
- name: Check if worker is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Debug tokens from first master
  debug:
    msg:
      - "Token: {{ hostvars[groups['masters'][0]]['kubeadm_token'] }}"
      - "Discovery: {{ hostvars[groups['masters'][0]]['kubeadm_discovery_token'] }}"

- name: Join worker to cluster
  shell: |
    kubeadm join \
      --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests \
      {{ k8s_api_ip }}:6443 \
      --token "{{ hostvars[groups['masters'][0]]['kubeadm_token'] }}" \
      --discovery-token-ca-cert-hash "{{ hostvars[groups['masters'][0]]['kubeadm_discovery_token'] }}"
  when: not kubelet_conf.stat.exists
